"use client";

import { useState } from "react";
import { Checkbox } from "@/components/ui/checkbox";
import HrSelect from "@/components/common/HrSelect";
import HrInput from "@/components/common/HrInput";

export default function ReportLayoutSettings() {
  const [details, setDetails] = useState({
    orgName: true,
    reportBasis: true,
    pageNumber: false,
    generatedBy: false,
    generatedDate: false,
    generatedTime: false,
  });

  const [layout, setLayout] = useState({
    density: "compact",
    design: "bordered",
    autoResize: true,
    paperSize: "a4",
    orientation: "portrait",
    font: "hind",
    margins: { top: 0.7, bottom: 0.7, left: 0.55, right: 0.2 },
  });

  const handleDetailChange = (key) => {
    setDetails({ ...details, [key]: !details[key] });
  };

  const handleMarginChange = (key, value) => {
    setLayout({
      ...layout,
      margins: { ...layout.margins, [key]: parseFloat(value) || 0 },
    });
  };

  return (
    <div className="flex gap-6 mb-30 ">
      {/* Left side - settings */}
      <div className="flex-1 space-y-6">
        {/* Details */}
        <div>
          <h3 className="font-semibold mb-2">Choose Details to Display</h3>
          <div className="grid grid-cols-3 gap-2 ">
            {Object.entries(details).map(([key, val]) => (
              <label key={key} className="flex items-center gap-2 text-sm">
                <Checkbox
                  checked={val}
                  onCheckedChange={() => handleDetailChange(key)}
                />
                {key === "orgName" && "Organization Name"}
                {key === "reportBasis" && "Report Basis"}
                {key === "pageNumber" && "Page Number"}
                {key === "generatedBy" && "Generated By"}
                {key === "generatedDate" && "Generated Date"}
                {key === "generatedTime" && "Generated Time"}
              </label>
            ))}
          </div>
        </div>

        {/* Layout */}
        <div>
          <h3 className="font-semibold mb-2">Report Layout</h3>
          <div className="grid grid-cols-2 gap-4">
            <HrSelect
              label="Table Density"
              value={layout.density}
              onChange={(e) => setLayout({ ...layout, density: e.target.value })}
              options={[
                { value: "compact", label: "Compact" },
                { value: "normal", label: "Normal" },
              ]}
            />
            <HrSelect
              label="Table Design"
              value={layout.design}
              onChange={(e) => setLayout({ ...layout, design: e.target.value })}
              options={[
                { value: "bordered", label: "Bordered" },
                { value: "striped", label: "Striped" },
              ]}
            />
          </div>

          <div className="mt-3">
            <label className="flex items-center gap-2 text-sm">
              <Checkbox
                checked={layout.autoResize}
                onCheckedChange={() =>
                  setLayout({ ...layout, autoResize: !layout.autoResize })
                }
              />
              Re-size the table and its font automatically to fit content
            </label>
          </div>

          {/* Paper size & orientation */}
          <div className="mt-4 flex gap-100">
            <div>
              <h4 className="text-sm font-medium mb-1">Paper Size</h4>
              <label className="flex items-center gap-2 text-sm">
                <input
                  type="radio"
                  name="paper"
                  checked={layout.paperSize === "a4"}
                  onChange={() => setLayout({ ...layout, paperSize: "a4" })}
                />
                A4
              </label>
              <label className="flex items-center gap-2 text-sm">
                <input
                  type="radio"
                  name="paper"
                  checked={layout.paperSize === "letter"}
                  onChange={() => setLayout({ ...layout, paperSize: "letter" })}
                />
                Letter
              </label>
            </div>

            <div>
              <h4 className="text-sm font-medium mb-1">Orientation</h4>
              <label className="flex items-center gap-2 text-sm">
                <input
                  type="radio"
                  name="orientation"
                  checked={layout.orientation === "portrait"}
                  onChange={() =>
                    setLayout({ ...layout, orientation: "portrait" })
                  }
                />
                Portrait
              </label>
              <label className="flex items-center gap-2 text-sm">
                <input
                  type="radio"
                  name="orientation"
                  checked={layout.orientation === "landscape"}
                  onChange={() =>
                    setLayout({ ...layout, orientation: "landscape" })
                  }
                />
                Landscape
              </label>
            </div>
          </div>

          {/* Font + margins */}
          <div className="grid grid-cols-2 gap-4 mt-10">
            <div className="mt-6">
               <HrSelect
              label="Font Family"
              value={layout.font}
              onChange={(e) => setLayout({ ...layout, font: e.target.value })}
              options={[
                { value: "hind", label: "Hind" },
                { value: "roboto", label: "Roboto" },
                { value: "arial", label: "Arial" },
              ]}
            />
            </div>
           

            <div>
              <h4 className="text-sm font-medium mb-1">Margins</h4>
              <div className="grid grid-cols-4 gap-2">
                {["top", "bottom", "left", "right"].map((pos) => (
                  <HrInput
                    key={pos}
                    label={pos.charAt(0).toUpperCase() + pos.slice(1)}
                    type="number"
                    step="0.01"
                    value={layout.margins[pos]}
                    onChange={(e) => handleMarginChange(pos, e.target.value)}
                  />
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Right side - preview */}
      <div className="w-80 border rounded-md shadow-sm p-3 bg-gray-50">
        <h4 className="font-semibold mb-2">Preview</h4>
        <div
          className="border rounded-md bg-white p-4 shadow-inner"
          style={{
            fontFamily: layout.font,
            paddingTop: `${layout.margins.top}in`,
            paddingBottom: `${layout.margins.bottom}in`,
            paddingLeft: `${layout.margins.left}in`,
            paddingRight: `${layout.margins.right}in`,
          }}
        >
          {details.orgName && (
            <p className="text-center text-sm font-medium">Admin</p>
          )}
          {details.reportBasis && (
            <p className="text-center text-sm font-semibold">Basis: Accrual</p>
          )}
          <table
            className={`w-full mt-2 border ${
              layout.design === "bordered"
                ? "border-gray-300"
                : "border-none"
            }`}
          >
            <tbody>
              {Array.from({ length: 6 }).map((_, i) => (
                <tr
                  key={i}
                  className={`border-t ${
                    layout.design === "striped" && i % 2 === 0
                      ? "bg-gray-100"
                      : ""
                  }`}
                >
                  {Array.from({ length: 4 }).map((_, j) => (
                    <td key={j} className="p-2 border-r"></td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
          <div className="flex justify-between text-xs mt-2 text-gray-500">
            {details.generatedBy && <span>Admin</span>}
            {details.pageNumber && <span>Page 1 of 1</span>}
            {details.generatedDate || details.generatedTime ? (
              <span>{new Date().toLocaleString()}</span>
            ) : null}
          </div>
        </div>
      </div>
    </div>
  );
}
